version: "3"
services:
  dns-server:
    container_name: dns-server
    hostname: dns-server
    image: technitium/dns-server:latest
    ports:
      - "5380:5380/tcp" #DNS web console (HTTP)
      - "53:53/udp" #DNS service
      - "53:53/tcp" #DNS service
    environment:
      - DNS_SERVER_DOMAIN=dns-server #The primary domain name used by this DNS Server to identify itself.
    volumes:
      - /Users/hyunho/workspace/private/dns/:/etc/dns # Change !!
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
    networks:
      dns:
        ipv4_address: 172.27.0.53
networks:
  dns:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/16
